config/routes.rb
Rails.application.routes.draw do
  root to: "pages#index"
  get '/about_us', to: "pages#about_us"
  # xxxxxxx/about_us

  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord

  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    # anasayfam
  end

  def about_us
    # hakkımızda
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :todo_params, only: [:create, :update]
  before_action :set_todo, only: [:edit, :update, :show, :destroy]
  
  def index
    @todos = Todo.all
  end

  def show
  end

  def new
    @todo = Todo.new
  end

  def update
    if @todo.update(todo_params)
      flash[:notice] = "Başarıyla güncelleme yapıldı"
      redirect_to todo_path(@todo)
    else
      render :edit
    end
  end

  def edit
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      flash[:notice] = "Başarıyla kayıt yapıldı"
      redirect_to todos_path
    else
      render :new
    end
  end

  def destroy
    @todo.destroy
    flash[:notice] = "Silme işlemi başarıyla gerçekleşti"
    redirect_to todos_path
  end

  private
    def set_todo
      @todo = Todo.find(params[:id])
    end

    def todo_params
      params.require(:todo).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IlkUygulamam</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about_us.html.erb
<h1>Hakkımızda sayfası</h1>
<%= link_to "Anasayfa", root_path %>

app/views/pages/index.html.erb
<h1>Anasayfaya hoşgeldiniz</h1>
<%= link_to "Hakkımızda sayfası", about_us_path %>

app/views/todos/_form.html.erb
<%= form_with(model: todo) do |f| %>

<% if todo.errors.any? %>
  <ul>
  <% todo.errors.each do |error| %>
    <li class="error"><%= error.full_message %></li>
  <% end %>
  </ul>
<% end %>

<%= f.label :body %>
<%= f.text_area :body%>

<hr>

<%= f.submit %>

<% end %>

app/views/todos/edit.html.erb
<h1> edit todo form</h1>

<%= render "form", todo: @todo %>

app/views/todos/index.html.erb
<p class="notice"><%= notice %></p>

<h1>todos index page</h1>
<%= link_to "New todo", new_todo_path %>
<hr>
<%- @todos.each do |t|%>
  <p><%= t.body %> <%= link_to "Show", todo_path(t) %> <%= link_to "Destory", todo_path(t), method: :delete %><%= link_to "Edit", edit_todo_path(t) %></p>
<% end %>

app/views/todos/new.html.erb
<h1> new todo form</h1>

<%= render "form", todo: @todo %>

app/views/todos/show.html.erb
<p class="notice"><%= notice %></p>
<h1><%= @todo.body %></h1>